### ISSUE TITLE
Not compatible with Coq.8.7

### ISSUE THREAD

**Issue by ildyria** [math-comp/finmap#15]
When trying to compile I get the following error.

```sh
git clone git@github.com:math-comp/finmap.git;
cd finmap;
make
```

which leads to:
```
File "./finmap.v", line 2309, characters 0-72:
Error:
Ltac call to "by (ssrhintarg)" failed.
Conversion test raised an anomalyAnomaly
                                 "Universe mathcomp.finmap.finmap.1389 undefined."
                                 Please report at http://coq.inria.fr/bugs/.
```

Admitting the lemma, leads to the following:

```
File "./finmap.v", line 2444, characters 0-63:
Error:
Ltac call to "by (ssrhintarg)" failed.
Conversion test raised an anomalyAnomaly
                                 "Universe mathcomp.finmap.finmap.1564 undefined."
                                 Please report at http://coq.inria.fr/bugs/.
```

**Comment by CohenCyril** [comment]
I worked around the problem. Thanks ejgallego for repporting to coq/coq.

**Comment by CohenCyril** [comment]
Actually thanks @matejkosik

**Comment by maximedenes** [comment]
@CohenCyril can you give a pointer to the coq/coq issue?

**Comment by matejkosik** [comment]
@CohenCyril You are welcome.

**Comment by strub** [comment]
Did you push the workaround? This is still failing here.

**Comment by CohenCyril** [comment]
Yes I did, what error message do you get?

**Comment by strub** [comment]
In fact, the opam package is still pointing to:

  https://github.com/Barbichu/finmap.git

2017-10-19 19:03 GMT+02:00 Cyril Cohen <notifications@github.com>:

**Comment by CohenCyril** [comment]
oops ok :)

**Comment by CohenCyril** [comment]
Fixed in PR https://github.com/coq/opam-coq-archive/pull/205

**Comment by ildyria** [comment]
@CohenCyril I did https://github.com/coq/opam-coq-archive/pull/204 a bit before. Shall I close it?

**Comment by gares** [comment]
Hem, @CohenCyril, maybe next time you find a bug in ssr (even if you manage to work around it) tell me ;-)

**Comment by maximedenes** [comment]
> tell me

No, please open an issue on the Coq bug tracker and assign it to Enrico or me.
