### ISSUE TITLE
totalType in ProdLexOrder and SeqProdOrder

### ISSUE THREAD

**Issue by mituharu** [math-comp/finmap#46]
Definitions of `latticeType` and `totalType` are identical in the modules ProdLexOrder and SeqProdOrder:

https://github.com/math-comp/finmap/blob/dd86e52d653d189a531a8782c3f3b1a69addaf0e/order.v#L3466-L3467
https://github.com/math-comp/finmap/blob/dd86e52d653d189a531a8782c3f3b1a69addaf0e/order.v#L3640-L3642

Probably you mean `Canonical orderType := OrderType (T * T') total` and `Canonical orderType := OrderType (seq T) total`, respectively?

**Comment by CohenCyril** [comment]
Thank you, I spotted that one just after releasing, along with a few other bugs and missing features which I will correct asap. (Expect a release 1.3.2 very soon).
Feel free to post more issues if you also find more, I would appreciate it.
