### ISSUE TITLE
compilation error due to Notation "[ 'fset[' key ] E | x : A , y : B ]"

### ISSUE THREAD

**Issue by erikmd** [math-comp/finmap#62]
as noticed by @affeldt-aist as well in [this comment](https://github.com/math-comp/finmap/commit/48c1330c43194c566410bb1dcb1af623b679cc2e), finmap.dev doesn't compile anymore with coq.dev and mathcomp.dev

See e.g. https://gitlab.com/math-comp/math-comp/-/jobs/463594590#L568 :

> 568 - File "./finmap.v", line 831, characters 0-154:
> 569 - Error: Notation "[ fset[ _ ] _ | _ : _ , _ : _ ]" is already defined
> 570 - at level 0 with arguments constr, constr at level 99, constr at level 99,
> 571 - constr at level 200, constr at level 99, constr
> 572 - while it is now required to be at level 0 with arguments constr, constr
> 573 - at level 99, constr at level 99, constr, constr at level 99, constr.

so this seems to come from the fact this notation is defined twice with incompatible levels:
https://github.com/math-comp/finmap/blob/48c1330c43194c566410bb1dcb1af623b679cc2e/finmap.v#L690-L693
https://github.com/math-comp/finmap/blob/48c1330c43194c566410bb1dcb1af623b679cc2e/finmap.v#L831-L833

Cc @CohenCyril

**Comment by CohenCyril** [comment]
Hi! I guess the proper fix is to have "Reserved Notation" and I think the second declaration (lines 831-833) is good enough.

**Comment by CohenCyril** [comment]
cf https://github.com/math-comp/finmap/pull/61#issuecomment-596475764
