### ISSUE TITLE
finmap for 1.12?

### ISSUE THREAD

**Issue by thery** [math-comp/finmap#80]
the current 1.5.0 fails on
```
File "./set.v", line 764, characters 7-23:
Error: Cannot apply lemma join_idPr
```

**Comment by CohenCyril** [comment]
This has been fixed in the current master cf https://github.com/math-comp/finmap/pull/77/files

**Comment by CohenCyril** [comment]
1.5.1 is released and in the pipeline of opam-coq-archive
